<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tart</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Tart</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.tart</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.tart</string>
			<key>swallow</key>
			<string>\\\s*\n</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|while|for|return|loop|break|continue|try|except|finally)\b</string>
			<key>name</key>
			<string>keyword.control.tart</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(public|private|protected)\b</string>
			<key>name</key>
			<string>keyword.visibility.tart</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(class|struct|enum|interface|namespace)\b</string>
			<key>name</key>
			<string>keyword.typename.tart</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(final|static)\b</string>
			<key>name</key>
			<string>storage.modifier.tart</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.tart</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.single.tart</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(True|False|None)\b</string>
			<key>name</key>
			<string>constant.language.tart</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:((0x\h*)|(\d+\.?\d*|\.\d+)(e[-+]?\d+)?)(l|u|f|ul)?j?)\b</string>
			<key>name</key>
			<string>constant.numeric.tart</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bool|byte|short|int|long|ubyte|ushort|uint|ulong|float|double|char|String)\b</string>
			<key>name</key>
			<string>support.type.builtin.tart</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(def|macro)\s+([-a-zA-Z0-9_]+)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.tart</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.tart</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.function.tart</string>
			<key>end</key>
			<string>\)\s*(\-\&gt;\s*([-a-zA-Z0-9_]+))?</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.type.tart</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.tart</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.multi.tart</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nested_braces</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arg_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arg_type</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.tart</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.keyword.tart</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.tart</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.function.tart</string>
			<key>match</key>
			<string>\b(def)\s+([-a-zA-Z0-9_]+)\s*\:\s*([-a-zA-Z0-9_]+)</string>
			<key>name</key>
			<string>meta.function.property.tart</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.tart</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.tart</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.function.tart</string>
			<key>match</key>
			<string>\b(def)\s*\[\](?:\s*\:\s*([-a-zA-Z0-9_]+))?</string>
			<key>name</key>
			<string>meta.function.index.tart</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(get|set)\s+\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.tart</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>variable.parameter.accessor.tart</string>
			<key>end</key>
			<string>\)\s*(\-\&gt;\s*([-a-zA-Z0-9_]+))?</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.type.tart</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.tart</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.accessor.tart</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nested_braces</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arg_keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arg_type</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.variable.tart</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.keyword.tart</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.tart</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(let|var)\s+([-a-zA-Z0-9_]+)\s*\:\s*(?:[-a-zA-Z0-9_]+)?</string>
			<key>name</key>
			<string>meta.definitiopn.variable.tart</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bget\b</string>
			<key>name</key>
			<string>storage.type.getter.tart</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(iterate|tostring|print|println|assert)\b</string>
			<key>name</key>
			<string>support.function.tart</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(range)\b</string>
			<key>name</key>
			<string>support.type.tart</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(self)\b</string>
			<key>name</key>
			<string>variable.language.tart</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>meta.brace.curly.tart</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>meta.brace.round.tart</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[|\]</string>
			<key>name</key>
			<string>meta.brace.square.tart</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|as|in|is|not|or)\b</string>
			<key>name</key>
			<string>keyword.operator.tart</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arg_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.keyword.tart</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:,|(?&lt;=\())\s*([-a-zA-Z0-9_]+)</string>
		</dict>
		<key>arg_type</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.tart</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\:\s*([-a-zA-Z0-9_]+)</string>
		</dict>
		<key>nested_braces</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nested_braces</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.tart</string>
	<key>uuid</key>
	<string>E064DC91-A366-4A75-ACB2-9914C1B766D1</string>
</dict>
</plist>
